App
  Logger
  KakaoChatbotSkill
    UserAuth
      UserRepository
        Repository
          Postgres
        Cache
          RedisGeneral
            Redis
    UserNickname
      UserRepository
        Repository
          Postgres
        Cache
          RedisGeneral
            Redis
    StoreFinder
      StoreState
        RedisGeneral
          Redis
        StoreRepository
          Repository
            Postgres
          RedisGeneral
            Redis
          Cache
            RedisGeneral
              Redis
      StoreRepository
        Repository
          Postgres
        RedisGeneral
          Redis
        Cache
          RedisGeneral
            Redis
    MenuDocument
      MenuRepository
        Cache
          RedisGeneral
            Redis
    OrderDocument
      RedisGeneral
        Redis
      OrderRepository
        Repository
          Postgres
      OrderMessage
        Message
          RedisMessage
            Redis
      StoreMessage
        Message
          RedisMessage
            Redis
        RedisGeneral
          Redis
    OrderSession
      RedisGeneral
        Redis
    OrderApprovalSession
      RedisGeneral
        Redis
    OrderPlacement
      OrderSession
        RedisGeneral
          Redis
      StoreState
        RedisGeneral
          Redis
        StoreRepository
          Repository
            Postgres
          RedisGeneral
            Redis
          Cache
            RedisGeneral
              Redis
      PaymentSession
        RedisGeneral
          Redis
        PaymentKakaopay
          HttpModule
      OrderMessage
        Message
          RedisMessage
            Redis
  PaymentCallbackGateway
    OrderApprovalSession
      RedisGeneral
        Redis
    OrderPlacement
      OrderSession
        RedisGeneral
          Redis
      StoreState
        RedisGeneral
          Redis
        StoreRepository
          Repository
            Postgres
          RedisGeneral
            Redis
          Cache
            RedisGeneral
              Redis
      PaymentSession
        RedisGeneral
          Redis
        PaymentKakaopay
          HttpModule
      OrderMessage
        Message
          RedisMessage
            Redis
    OrderMessage
      Message
        RedisMessage
          Redis
  OrderApproval
    PaymentKakaopay
      HttpModule
    OrderRepository
      Repository
        Postgres
    OrderMessage
      Message
        RedisMessage
          Redis
    StoreMessage
      Message
        RedisMessage
          Redis
      RedisGeneral
        Redis
  Alert
    UserAuth
      UserRepository
        Repository
          Postgres
        Cache
          RedisGeneral
            Redis
    OrderMessage
      Message
        RedisMessage
          Redis
    KakaoChatbotEvent
      HttpModule